### ISSUE TITLE
Support costume host (instead of '*') for Spring Boot Starter

### ISSUE THREAD

**Issue by DestBro** [Kotlin/kotlin-jupyter#475]
Support costume host (instead of '*') for Spring Boot Starter.

Right now there is a way to config only the ports via:
```
kotlin:
  jupyter:
    kernel:
      ports:
        hb: 9091
        shell: 9092
        control: 9093
        stdin: 9094
        iopub: 9095

```

For security reasons I would like that instead of host "*" to use just "localhost".
